name: dartMock
description: A simple mock application for flutter web create by dart.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http_server: ^0.9.8+3

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
